### ISSUE TITLE
Have separate Steroids.json for each enviroment 

### ISSUE THREAD

**Issue by rifhanakram** [99xt/steroidslibrary#28]
Currently the steroids json needs to be changed when switching between enviroments 

**Suggestion** 
- have three separate steroid json files named as -> steroids.<env>.json & one common **steroids.json**
- have a gulp task that takes in the argument of the env and copies the relevant json content and replaces the content in **steroids.json** with it. 

_Note_
we can either have the enviroment passed in as an argument or we can have it defined in our enviroment as ENV.

**Comment by supuncodes** [comment]
A feature was added in steroids to manually change the filename of the configuration file (steroids.json)
